version: "3.8"

services: 
  vpn-server: 
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard-server
    environment: 
      - PUID=1000
      - PGID=1000
      - SERVERURL=vpn-server
      - PEERS=1 
      - SERVERPORT=51820
    volumes: 
      - ./config/server:/config
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1

  vpn-client: 
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard-client
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    volumes: 
      - ./config/client:/config
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
